Moyart
gsbelarus/gdmn4 pull request #3
Opened 2023-03-07 20:25 UTC by maisiukartyom

Issue 1 сделал. Оставляю на проверку

2023-03-07 20:48 UTC, gsbelarus requested changes
поправь:

1. мы будем использовать styled-components и не будем использовать отдельные css файлы
2. мы будем использовать стандартный fetch вместо axios

2023-03-07 20:53 UTC, gsbelarus commented on packages/web/src/app/components/organization/Organization.tsx
> +    axios.get(`http://localhost:3000/getUsers?org=${id}`).then(res => {
если используешь внешнюю переменную (по отношению к useEffect, то ее надо прописать в зависимостях useEffect).

2023-03-07 20:56 UTC, gsbelarus commented on packages/server/src/main.ts
> +  const email = ctx.request.body.email
все входящие объекты надо проверять через валидатор. посмотри как сделана проверка и обработка ошибок валидации на примере рест поинтов login и register

2023-03-07 20:57 UTC, gsbelarus commented on packages/server/src/main.ts
> +  const user = await User.findOne({email: email})
здесь красивее исползовать сокращенную форму { email }

2023-03-07 20:57 UTC, gsbelarus commented on packages/server/src/main.ts
> +    const organization = new Organization({name: ctx.request.body.name})
точку с запятой мы ставим в конце строки.

2023-03-07 20:59 UTC, gsbelarus commented on packages/server/tsconfig.app.json
> +  "include": ["src/**/*.ts", "src/db/membershipModel.ts"]
а разве не должен подхватить этот файл по первой маске?

2023-03-07 21:36 UTC, gsbelarus commented
я смержил свои изменения в твою ветку. сделай у себя `git pull` и потом `npm install` в корне проекта.

затем внеси исправления закомить и сделай пуш. они добавятся к этому пул реквесту.

2023-03-08 09:48 UTC, maisiukartyom commented on packages/server/tsconfig.app.json
> +  "include": ["src/**/*.ts", "src/db/membershipModel.ts"]
Да, убрал лишнее. Видимо vscode автоматом дописал, когда я случайно удалил и вернул этот файл.

2023-03-08 18:00 UTC, maisiukartyom commented on packages/web/src/app/components/organization/Organization.tsx
> +    axios.get(`http://localhost:3000/getUsers?org=${id}`).then(res => {
Исправлено

2023-03-08 18:00 UTC, maisiukartyom commented on packages/server/src/main.ts
> +  const email = ctx.request.body.email
Добавил валидацию для всех запросов

2023-03-08 18:00 UTC, maisiukartyom commented on packages/server/src/main.ts
> +    const organization = new Organization({name: ctx.request.body.name})
Везде точка с запятой

2023-03-09 18:49 UTC, gsbelarus approved these changes

2023-03-09 18:49 UTC, merged